IRCI1 - Analyse I - Chapitre 2
nenglebert/Syntheses pull request #182
Opened 2018-11-04 22:12 UTC by quentinguidee

Corrections diverses

2018-11-04 23:58 UTC, f380cedric requested changes

2018-11-04 23:58 UTC, f380cedric commented on IRCI1/Analyse I/Analyse I - Nicolas Englebert.tex
> +% Premier espèce ou premier espace ??
À supprimer

2018-11-04 23:58 UTC, f380cedric commented on IRCI1/Analyse I/Analyse I - Nicolas Englebert.tex
> +La limite à gauche et à droite existent mais sont différentes, on parle de \textit{discontinuité de première espace}.\\
C'est espèce (et non espace), peux-tu corriger ?

2018-11-05 18:21 UTC, f380cedric approved these changes

2018-11-05 18:39 UTC, f380cedric requested changes
Cf.  https://github.com/nenglebert/Syntheses/pull/183#pullrequestreview-171697252

2018-11-05 19:18 UTC, quentinguidee commented
Voilà tout est sur le Patch 3

2018-11-05 20:07 UTC, f380cedric commented
Par "déplacer ce commit (quentinguidee/Syntheses@f240b73) sur #182" j'entendais uniquement le commit quentinguidee/Syntheses@f240b73 (sans quentinguidee@3130651248a497d7e10abd65428d2a6262fbf566). Mais c'est pas grave. Je vais m'arranger

2018-11-05 20:45 UTC, closed without merging