IRCI1 - Analyse I - Ch2
nenglebert/Syntheses pull request #183
Opened 2018-11-05 07:31 UTC by quentinguidee

Corrections diverses

2018-11-05 18:33 UTC, f380cedric requested changes
Il faudrait déplacer ce commit (quentinguidee@f240b73abe0fb0339d5c9f008f54fda4b6130056) sur #182 (i.e. le déplacer de ta branche [quentinguidee:path-4](https://github.com/quentinguidee/Syntheses/tree/patch-4) à ta branche [quentinguidee:path-3](https://github.com/quentinguidee/Syntheses/tree/patch-3).

2018-11-05 20:14 UTC, f380cedric commented
@quentinguidee, as-tu (ou auras-tu) d'autres modifications pour la synthèse de Physique générale BA1 ?

2018-11-05 20:43 UTC, quentinguidee commented
Non il n'y avait que ces 2 modifications récentes dans Phys Générale

2018-11-05 20:48 UTC, quentinguidee commented
@f380cedric je sais pas où demander ça, mais de quelle manière tu préfères que je fasses mes commit pour qu'on s'en sorte?

2018-11-05 20:57 UTC, merged

2018-11-05 21:29 UTC, f380cedric commented
Les commits ne sont pas si importants, si ce ne sont que des corrections de coquilles, je peux les regrouper en un seul commit (histoire de n'avoir qu'un commit dans l'historique pour la correction d'Analyse I Chapitre 2).
Par contre, ça devient ennuyant si dans un même pull request tu mets des commits de cours différents. 
Ainsi, je préférerai que tu crées des pull requests avec _Année - Cours - Chapitre_ comme titre (le chapitre pouvant être optionnel) , ne contenant que des corrections de coquilles de la partie correspondante au titre.
Aussi, essayons d'éviter d'ouvrir plusieurs pull requests pour un même titre (comme ça a pu être le cas pour _Analyse I - Chapitre 2_ dans #182 et #183), propose un pull request quand tu as fini ou précise en commentaire du pull request qu'il n'est pas complet et que d'autres commits vont venir s'ajouter.

Après, tout dépend de tes connaissances en git, je n'ai pas de problème si tu ouvres un pull request avec les corrections d'Analyse I Chapitre 3 et de Physique Générale Magnétostatique, si tu réécris ton historique de branche pour regrouper les commits de chaque cours entre eux (i.e. 1 commit pour Analyse Chapitre 3, 1 commit pour Magnétostatique).

2018-11-05 21:36 UTC, quentinguidee commented
Ok merci beaucoup! Et pour recompiler les fichiers quand les corrections seront terminées je te laisse le soin de le faire quand je te le signalerai?

2018-11-05 21:40 UTC, f380cedric commented
Oui, je ferai un commit dans lequel j'actualiserai les pdfs 😉

2018-11-05 21:41 UTC, quentinguidee commented
Ok parfait merci bcp!

2018-11-06 07:40 UTC, nenglebert commented
Hello Quentin!
Merci pour tes différentes corrections (et merci à Cédric pour le suivi!) ! :) Si tu comptes en faire plusieurs, il pourrait être intéressant que tu travailles en version locale pour pouvoir directement mettre à jour le pdf (puis c'est plus agréable que via le site). Si ça t'intéresse et que tu as des questions, on peut se fixer un rendez-vous pour en parler :)